language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

after_script:
  - php composer/bin/test-reporter