language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
install: composer install --dev
before_script:
  - git config --global user.email "dev.pmill@gmail.com"
  - git config --global user.name "pmill"
after_script:
  - php vendor/bin/test-reporter